### ISSUE TITLE
Userscript

### ISSUE THREAD

**Issue by Keith94** [Natronium/tco-unmangler#1]
Any chance you could make an alternative userscript version? I couldn't find any scripts that work properly.

**Comment by Riajyuu** [comment]
Agreed.
Perhaps greasyfork.org is rather proper

**Comment by natronium** [comment]
Sorry it took me more than two months to get around to fixing this. Since I'd already wrote the extension to be compatible with firefox and chrome, I just needed to add a metadata block and rename the file. Going to https://gitlab.com/Na/tco-unmangler/raw/master/tco-unmangler.user.js should prompt you to install the unmangler as a userscript.

I don't actually use any userscripts, so let me know if something userscripty is broken.

**Comment by Keith94** [comment]
Thanks @Natronium, the script is active in Greasemonkey but I think it's not working correctly.
Still shows "t.co" on link hover/copy. Can you try it?

![nvidia share_2017-12-15_12-40-40](https://user-images.githubusercontent.com/5490615/34059758-49a1f9a6-e195-11e7-94c6-5d143c8f6257.png)

**Comment by natronium** [comment]
Welp. Looks like I missed a spot. I see the same behaviour, but *only* for profile URLs, other t.co links are getting unmangled. Thanks for pointing that out! I can't fix it right this instant, but I've added a shiny new issue (#2) to track it

**Comment by Keith94** [comment]
EDIT: nevermind, my mistake

Thanks for filing the issue
